--- 
user: deploy
group: deploy
wait: 30
environment: production
servers: 1
threaded: true
no-epoll: true
daemonize: true
tag: sloth-run
log: /home/deploy/apps/shared/log/thin.log
pid: /home/deploy/apps/shared/tmp/pids/thin.pid
socket: /home/deploy/apps/shared/tmp/sockets/thin.sock
chdir: /home/deploy/apps/sloth-run/current
