--- 
user: deploy
group: deploy
wait: 30
log: /home/deploy/apps/shared/log/thin.log
environment: production
servers: 1
threaded: true
no-epoll: true
daemonize: true
chdir: /home/deploy/apps/sloth-run/current
tag: sloth-run
